# Generated by Django 5.0.1 on 2024-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_consultationrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationrequest',
            old_name='topic_title',
            new_name='topic_section',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='topic_code',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='topic_id',
            field=models.CharField(choices=[('ADM01', 'ADM01'), ('ADM02', 'ADM02'), ('ADM03', 'ADM03'), ('REG04', 'REG04'), ('REG05', 'REG05'), ('UP01', 'UP01'), ('UP02', 'UP02'), ('UP03', 'UP03'), ('UP03-1', 'UP03.1'), ('UP05', 'UP05'), ('UP06', 'UP06'), ('UP07', 'UP07'), ('UP08', 'UP08'), ('UP09', 'UP09'), ('UP10', 'UP10'), ('UP11', 'UP11'), ('UP12', 'UP12'), ('UP13', 'UP13'), ('UP14', 'UP14'), ('UP17', 'UP17'), ('UP18', 'UP18'), ('UP20-1', 'UP20.1'), ('UP24', 'UP24'), ('UP25', 'UP25'), ('UP29', 'UP29'), ('UP30', 'UP30')], default='default_value_here', max_length=10),
        ),
    ]
