# Generated by Django 5.0.1 on 2024-02-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_topic_title_consultationrequest_topic_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedconsultation',
            old_name='topic_code',
            new_name='topic_id',
        ),
        migrations.RenameField(
            model_name='completedconsultation',
            old_name='topic_title',
            new_name='topic_section',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='full_name',
        ),
    ]
